19:01:31.131406 - Connection ERROR: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
20:15:48.486061 - Connection ERROR: list index out of range
12:54:07.553575 - Connection ERROR: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
12:54:08.760348 - Connection ERROR: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot1480667214:AAFuuQu7aF6Cx1wIDIFGwnsdCQDAeDqZU-s/getUpdates?offset=441343829&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022FCEF5B520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
12:54:09.764662 - Connection ERROR: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot1480667214:AAFuuQu7aF6Cx1wIDIFGwnsdCQDAeDqZU-s/getUpdates?offset=441343829&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022FCEF6C760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
12:54:13.246350 - Connection ERROR: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
12:58:15.952067 - Connection ERROR: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
13:18:59.462183 - Connection ERROR: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
13:19:02.267433 - Connection ERROR: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot1480667214:AAFuuQu7aF6Cx1wIDIFGwnsdCQDAeDqZU-s/getUpdates?offset=441343829&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022FCEF5BC40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
13:22:24.711833 - Connection ERROR: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
